name: Deploy Next.js App (EC2 + PM2)

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Vào thư mục project
          cd ~/portfolio

          # Kéo code mới nhất
          git fetch --all
          git reset --hard origin/master

          # Cài dependencies (nếu có thay đổi)
          npm install --production

          # Build lại project
          npm run build

          # Restart PM2
          pm2 start npm --name "portfolio-app" -- start || pm2 restart portfolio-app
          pm2 save
